# This is the main configuration file for Pork2b2tBot.
# Not sure what to say
# Anything that needs a description has one

login:
  # Whether or not to authenticate with mojang or use a cracked account
  # Default: false
  doAuthentication: false

  # Your username goes here.
  # If you're using authentication, use your email like you would in the launcher.
  # If not, enter the username you want to use.
  # Default: Steve
  username: 'Steve'

  # Your password goes here.
  # If you're using authentication, use your email like you would in the launcher.
  # If not, enter anything you feel like
  # Default: password
  password: 'password'

client:
  # The IP of the server to connect to.
  # This is required! Without it nothing can happen.
  # Default: mc.example.com
  hostIP: 'mc.example.com'

  # The IP of the server to connect to.
  # This is required! Without it nothing can happen.
  # You can probably leave this alone unless you know what you're doing.
  # Default: 25565
  hostPort: 25565

chat:
  # Whether or not we will process chat messages.
  # Leave this off unless you know what you're doing.
  # Default: false
  doProcess: false

  spam:
    # Whether or not to spam chat.
    # Default: false
    doSpam: false

    # The delay (in milliseconds) between spam messages.
    # Default: 10000
    delay: 10000

    # A list of all spam messages that can be sent
    # Every [delay] milliseconds a random message is picked from this list and sent in chat
    # More features are planned for this, but not implemented yet
    # Default: not putting it here, just remeber it or sth idk kek
    messages:
      - 'I sexually Identify as an Attack Helicopter.'
      - 'Ever since I was a boy I dreamed of soaring over the oilfields dropping hot sticky loads on disgusting foreigners.'
      - 'People say to me that a person being a helicopter is Impossible and I’m fucking retarded but I don’t care, I’m beautiful.'
      - 'I’m having a plastic surgeon install rotary blades, 30 mm cannons and AMG-114 Hellfire missiles on my body.'
      - 'From now on I want you guys to call me “Apache” and respect my right to kill from above and kill needlessly.'
      - 'If you can’t accept me you’re a heliphobe and need to check your vehicle privilege.'
      - 'Thank you for being so understanding.'

misc:
  # Whether or not to automagically respawn after dying
  # Default: true
  autorespawn: true

  # Whether or not to antiAFK.
  # Rotates you around and swings to prevent you from being kicked.
  # Default: true
  antiafk: true

  # Automatically relogs after getting kicked.
  # Waits 10 seconds.
  # Default: true
  autoreconnect: true

websocket:
  # Whether or not to run the websocket server.
  # A demonstration can be found at http://www.daporkchop.net/pork2b2tbot
  # You can leave this off unless you REALLY know what you're doing.
  # I'm not providing any support for this option. At all. Period.
  # Default: false
  doWebsocket: false

  # What port to run the websocket server on.
  # Default: 8888
  port: 8888

stats:
  # Whether or not to record stats and save them to a file.
  # Still WIP, don't expect anything from this
  # Default: false
  doStats: false

server:
  # Whether or not to run a server inside the bot
  # Useful for moving the bot while still having it run
  # Default: true
  doServer: true

  # The port to run the server on
  # Default: 25565
  port: 25565

  # The host to listen on
  # By default we listen on all addresses
  # Default: 0.0.0.0
  address: '0.0.0.0'

  # Whether or not the server will run in online mode.
  # Default: false
  doAuth: false

  # Only users with these names will be able to connect.
  # Leave at "" to allow anyone to connect.
  # e.g.
  # whiteListUser:
  #   - "DaPorkchop_"
  #   - "0x22"
  # Default: ""
  whiteListUser:
  - ""

interface:
  # Whether or not to open a GUI
  # If you're running headless then disable this!!!
  # Default: true
  doGUI: true

# Don't touch this!
config-version: 6


